SHELL = %SystemRoot%/System32/cmd.exe
CC = gcc
RM = del /q

CFLAGS = -Wall -msse2 -mfpmath=sse
DEBUG = -O2
#DEBUG = -g

all: ctt.exe triangle.exe

ctt.exe: ctt.c ../util.c ../common.h
	$(CC) $(CFLAGS) $(DEBUG) -I.. ctt.c ../util.c -o ctt.exe -lm

triangle.exe: triangle.c triangle.h
	$(CC) $(CFLAGS) $(DEBUG) triangle.c -o triangle.exe -lm

clean:
	$(RM) ctt.o* util.o* ctt.exe
	$(RM) triangle.o* triangle.exe
